spring.application.name=TodoIntership

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
supabase.url=${SUPABASE_URL}
supabase.key=${SUPABASE_KEY}

springdoc.swagger-ui.path=/swagger-ui.html
